name: SAP BTP CF Login Test

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  login-to-cf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloud Foundry CLI
        run: |
          # Add the Cloud Foundry tap and install the CLI
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
          echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf8-cli

      - name: Verify CF CLI installation
        run: cf version

      - name: Log in to Cloud Foundry
        run: |
          cf login -a ${{ secrets.CF_API_ENDPOINT }} -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o ${{ secrets.CF_ORG }} -s ${{ secrets.CF_SPACE }}
        env:
          CF_API_ENDPOINT: ${{ secrets.CF_API_ENDPOINT }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}