name: Test ECR Image Pull

# on:
#   push:
#     branches:
#       - main

jobs:
  test-ecr-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional for now)
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
          registry-type: private

      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cf-test:cf-cli

      - name: Run container and verify CF CLI
        run: |
          docker run --rm ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/cf-test:cf-cli

      - name: Build Go app
        run: |
          mkdir build
          go build -o build/app