name: Deployment to Cloud Foundry

# on:
#   push:
#     branches:
#       - main

jobs:
  deploy-to-cf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloud Foundry CLI
        run: |
          # Add the Cloud Foundry tap and install the CLI
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
          echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf8-cli

      - name: Verify CF CLI installation
        run: cf version
      
      - name: Install protoc
        run: |
          PROTOC_ZIP=protoc-29.3-linux-x86_64.zip
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v29.3/$PROTOC_ZIP
          sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
          sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
          rm -f $PROTOC_ZIP
      
      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.6
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Verify protoc and plugins
        run: |
          echo "Protoc version:"
          protoc --version

          echo "Check protoc-gen-go location:"
          which protoc-gen-go || echo "protoc-gen-go not found"

          echo "Protoc-gen-go version (if available):"
          protoc-gen-go --version || echo "protoc-gen-go doesn't support --version"

          echo "List of protoc plugins in PATH:"
          ls -l $(go env GOPATH)/bin | grep protoc-gen

      - name: Go Build
        uses: actions/setup-go@v5
        run: |
          GOOS=linux GOARCH=amd64 
          go build
