name: Build and Upload

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Go app
        run: go build -o myapp .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upload to Google Drive
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          FOLDER_ID: ${{ secrets.GCP_FOLDER_ID }}
        run: python upload_to_gdrive.py
